package aurora

import (
	"math/rand"
)

var quotes = []string{
	`"I know I'm a handful but that's why you got two hands." - Unknown`,
	`"Failure is the condiment that gives success its flavor." - Truman Capote`,
	`"If you think you are too small to be effective, you have never been in the dark with a mosquito." - Betty Reese`,
	`"Taking naps sounds so childish. I prefer to call them horizontal life pauses." - Unknown`,
	`"I walk around like everything's fine, but deep down, inside my shoe, my sock is sliding off." - Unknown`,
	`"If we're not meant to have midnight snacks, why is there a light in the fridge?" - Unknown`,
	`"The best thing about the future is that it comes one day at a time." - Abraham Lincoln`,
	`"I'm not good at advice. Can I interest you in a sarcastic comment?" - Chandler Bing`,
	`"My ability to turn good news into anxiety is rivaled only by my ability to turn anxiety into chin acne." - Tina Fey`,
	`"So it turns out that being an adult is really just Googling how to do stuff." - Unknown`,
	`"It's okay to look at the past and the future. Just don't stare." - Lisa Lieberman-Wang`,
	`"Always remember that you are unique - just like everybody else." - Unknown`,
	`"Would I rather be feared or loved? Easy. Both. I want people to be afraid of how much they love me." - Michael Scott, The Office`,
	`"All you need is love. But a little chocolate now and then doesn't hurt." - Charles M. Schulz`,
	`"Before you marry a person, you should first make them use a computer with slow Internet to see who they really are." - Will Ferrell`,
	`"I love being married. It's so great to find one special person you want to annoy for the rest of your life." - Rita Rudner`,
	`"If love is the answer, can you please rephrase the question?" - Lily Tomlin`,
	`"Love can change a person the way a parent can change a baby—awkwardly, and often with a great deal of mess." - Lemony Snicket`,
	`"Love is a fire. But whether it is going to warm your hearth or burn down your house, you can never tell." - Joan Crawford`,
	`"A successful marriage requires falling in love many times, always with the same person." - Mignon McLaughlin`,
	`"I love you with all my belly. I would say my heart, but my belly is bigger." - Unknown`,
	`"The four most important words in any marriage — I'll do the dishes." - Unknown`,
	`"I love you more than coffee but not always before coffee." - Unknown`,
	`"I like long romantic walks down every aisle at Target." - Unknown`,
	`"You know that tingly little feeling you get when you like someone? That's your common sense leaving your body." - Unknown`,
	`"I choose a lazy person to do a hard job, because a lazy person will find an easy way to do it." - Bill Gates`,
	`"Doing nothing is very hard to do… you never know when you're finished." - Leslie Nielsen`,
	`"It takes less time to do a thing right, than it does to explain why you did it wrong." - Henry Wadsworth Longfellow`,
	`"Most of what we call management consists of making it difficult for people to get their work done." - Peter Drucker`,
	`"It is better to have one person working with you than three people working for you." - Dwight D. Eisenhower`,
	`"The best way to appreciate your job is to imagine yourself without one." - Oscar Wilde`,
	`"I hate when I lose things at work, like pens, papers, sanity, and dreams." - Unknown`,
	`"Creativity is allowing yourself to make mistakes. Art is knowing which ones to keep." - Scott Adams`,
	`"My keyboard must be broken, I keep hitting the escape key, but I'm still at work." - Unknown`,
	`"Work is against human nature. The proof is that it makes us tired." - Michel Tournier`,
	`"The reward for good work is more work." - Francesca Elisia`,
	`"Executive ability is deciding quickly and getting somebody else to do the work." - Earl Nightingale`,
	`"We put the 'fun' in dysfunctional." - Unknown`,
	`"Happiness is having a large, loving, caring, close-knit family in another city." - George Burns`,
	`"The informality of family life is a blessed condition that allows us all to become our best while looking our worst." - Marge Kennedy`,
	`"Families are like fudge - mostly sweet with a few nuts." - Unknown`,
	`"Being part of a family means smiling for photos." - Harry Morgan`,
	`"Family ties mean that no matter how much you might want to run from your family, you can't." - Unknown`,
	`"The advantage of growing up with siblings is that you become very good at fractions." - Robert Brault`,
	`"Children really can brighten up a house, because they never turn the lights off." - Ralph Bus`,
	`"The reason grandparents and grandchildren get along so well is that they have a common enemy." - Sam Levenson`,
	`"One day you will do things for me that you hate. That is what it means to be family." - Jonathan Safran Foer`,
	`"It's fun to complain with someone. Nothing brings us together more than complaining about other people." - Lew Schneider`,
	`"Friends are people who know you really well and like you anyway." - Greg Tamblyn`,
	`"It is one of the blessings of old friends that you can afford to be stupid with them." - Ralph Waldo Emerson`,
	`"There is nothing better than a friend, unless it is a friend with chocolate." - Linda Grayson`,
	`"If you have friends who are as weird as you, then you have everything." - Unknown`,
	`"We are best friends. Always remember that if you fall, I will pick you up... after I finish laughing." - Unknown`,
	`"Real friends don't get offended when you insult them. They smile and call you something even more offensive." - Unknown`,
	`"I'm sick of following my dreams, man. I'm just going to ask where they're going and hook up with 'em later." - Mitch Hedberg`,
	`"Gentlemen, you can't fight in here. This is the war room." - President Merkin Muffley (Peter Sellers), Dr. Strangelove`,
	`"My mother always used to say: The older you get, the better you get, unless you're a banana." - Rose (Betty White), The Golden Girls`,
	`"Halloween is the beginning of the holiday shopping season. That's for women. The beginning of the holiday shopping season for men is Christmas Eve." - David Letterman`,
	`"Before you criticize someone, you should walk a mile in their shoes. That way when you criticize them, you are a mile away from them and you have their shoes." - Jack Handey`,
	`"Looks like you've been missing a lot of work lately." - Bob, Office Space`,
	`"Clothes make the man. Naked people have little or no influence in society." - Mark Twain`,
	`"Before you marry a person, you should first make them use a computer with slow Internet to see who they really are." - Will Ferrell`,
	`"I love being married. It's so great to find that one special person you want to annoy for the rest of your life." - Rita Rudner`,
	`"Ned, I would love to stand here and talk with you—but I'm not going to." - Phil Connors (Bill Murray), Groundhog Day`,
	`"When your mother asks, 'Do you want a piece of advice?' it is a mere formality. It doesn't matter if you answer yes or no. You're going to get it anyway." - Erma Bombeck`,
	`"I want my children to have all the things I couldn't afford. Then I want to move in with them." - Phyllis Diller`,
	`"Never follow anyone else's path. Unless you're in the woods and you're lost and you see a path. Then by all means follow that path." - Ellen DeGeneres`,
	`"Insomnia sharpens your math skills because you spend all night calculating how much sleep you'll get if you're able to fall asleep right now." - Unknown`,
	`"Breaking up is like knocking over a Coke machine. You can't do it in one push; you got to rock it back and forth a few times, and then it goes over." - Jerry (Jerry Seinfeld), Seinfeld`,
	`"I'm not superstitious, but I am a little stitious." - Michael Scott, The Office`,
	`"I walk around like everything's fine, but deep down, inside my shoe, my sock is sliding off." - Unknown`,
	`"I haven't spoken to my wife in years. I didn't want to interrupt her." - Rodney Dangerfield`,
	`"I used to sell furniture for a living. The trouble was, it was my own." - Les Dawson`,
	`"There's nothing wrong with you that an expensive operation can't prolong." - Monty Python`,
	`"Someone asked me, if I were stranded on a desert island what book would I bring: ‘How to Build a Boat.'" - Steven Wright`,
	`"Surely you can't be serious." "I am serious. And don't call me Shirley." - Airplane!`,
	`"There is no sunrise so beautiful that it is worth waking me up to see it." - Mindy Kaling`,
	`"You know you've reached middle age when you're cautioned to slow down by your doctor, instead of by the police." - Joan Rivers`,
	`"Truth hurts. Maybe not as much as jumping on a bicycle with a seat missing, but it hurts." - Naked Gun`,
	`"My Mama says that alligators are ornery because they got all them teeth and no toothbrush." - The Waterboy`,
	`"I never feel more alone than when I'm trying to put sunscreen on my back." - Jimmy Kimmel`,
	`"Marriage is like an unfunny, tense version of Everybody Loves Raymond, but it doesn't last 22 minutes. It lasts forever." - Pete, Knocked Up`,
	`"Being a mom means never buying the right amount of produce. Either everyone suddenly loves grapes, or fruit flies are congregating around my rotting bananas." - Lessons from the Minivan`,
	`"I'm not insane. My mother had me tested." - Sheldon Cooper, The Big Bang Theory`,
	`"There are only three ages for women in Hollywood: babe, district attorney, and Driving Miss Daisy." - Elise, The First Wives Club`,
	`"Bride or groom?" "It should be perfectly obvious I'm neither!" - Four Weddings and a Funeral`,
	`"Describe your perfect date." "April 25. Because it's not too hot and not too cold. All you need is a light jacket." - Miss Congeniality`,
	`"Speaking in front of a crowd is the number one fear of the average person. Number two is death. This means to the average person, if you have to be at a funeral, you'd rather be in the casket than doing the eulogy." - Jerry Seinfeld`,
	`"There's just two things keeping me from dancing in that show." "Your feet?" - I Love Lucy`,
	`"Common sense is like deodorant. The people who need it most never use it." - Unknown`,
	`"How's a beer sound, Norm?" "I don't know, I usually finish before they get a word in." - Cheers`,
	`"If I woke up tomorrow with my head sewn to the carpet, I wouldn't be more surprised." - Clark Griswold, National Lampoon's Christmas Vacation`,
	`"There's nothing simpler than avoiding people you don't like. Avoiding one's friends, that's the real test." - Downton Abbey`,
	`"If I'm not back in five minutes, just wait longer." - Ace Ventura`,
	`"The only thing that separates us from the animals is our ability to accessorize." - Steel Magnolias`,
	`"I'm at a place in my life when errands are starting to count as going out." - Unknown`,
	`"Never be attracted by a bargain in plastic surgery and sushi." - Graham Norton`,
	`"Here's all you have to know about men and women: Women are crazy, men are stupid. And the main reason women are crazy is that men are stupid." - George Carlin`,
	`"When I'm in social situations, I always hold onto my glass. It makes me feel comfortable and secure and I don't have to shake hands." - Larry David`,
	`"As you get older, three things happen. The first is your memory goes, and I can't remember the other two." - Norman Wisdom`,
	`"Why can't you just be happy for me and then go home and talk behind my back later like a normal person?" - Bridesmaids`,
	`"Anyone who lives within their means suffers from a lack of imagination." - Oscar Wilde`,
	`"I never forget a face—but in your case, I'll be glad to make an exception." - Groucho Marx`,
	`"Here's something to think about: How come you never see a headline like ‘Psychic Wins Lottery'?" - Jay Leno`,
	`"A day without sunshine is like, you know, night." - Steve Martin`,
	`"My therapist told me the way to achieve true inner peace is to finish what I start. So far I've finished two bags of M&Ms and a chocolate cake. I feel better already." - Dave Barry`,
	`"Never do anything out of hunger. Not even eating." - True Detective`,
	`"You know you're getting old when you stoop to tie your shoelaces and wonder what else you could do while you're down there." - George Burns`,
	`"To call you stupid would be an insult to stupid people!" - A Fish Called Wanda`,
	`"Accept who you are. Unless you're a serial killer." - Ellen DeGeneres`,
	`"My ability to turn good news into anxiety is rivaled only by my ability to turn anxiety into chin acne." - Tina Fey`,
	`"I remember it like it was yesterday. Of course, I don't really remember yesterday all that well." - Dory, Finding Dory`,
	`"I don't have to take this abuse from you; I've got hundreds of people dying to abuse me." - Dr. Peter Venkman, Ghostbusters`,
	`"Pull over." "No, it's a cardigan. But thanks for noticing." - Dumb and Dumber`,
	`"If we're going to pay this much for crab, it better sing and dance and introduce us to the Little Mermaid." - Date Night`,
	`"I prefer not to think before speaking. I like being as surprised as everyone else by what comes out of my mouth." - Unknown`,
	`"Never put off till tomorrow what you can do the day after tomorrow just as well." - Mark Twain`,
	`"I can't end my messages with Love, Shaq because the B-52s ruined that for me." - Meme attributed to Shaquille O'Neal`,
	`"Thanksgiving dinners take 18 hours to prepare. They are consumed in 12 minutes. Half-times take 12 minutes. This is not a coincidence." - Erma Bombeck`,
	`"Insanity runs in my family. It practically gallops." - Arsenic and Old Lace`,
	`"You know you're getting old when you stoop to tie your shoelaces and wonder what else you could do while you're down there." - George Burns`,
	`"Why yes, I can carry on a conversation made up entirely of movie quotes." - Unknown`,
	`"I like long walks, especially when they are taken by people who annoy me." - Noel Coward`,
	`"Trying is the first step toward failure." - Homer Simpson, The Simpsons`,
	`"I have a lot of growing up to do. I realized that the other day inside my fort." - Zach Galifianakis`,
	`"The Only time there is peace is only when njoy is cooking ." - Mama`,
}

func Quote() string {
	randomIndex := rand.Intn(len(quotes))
	return quotes[randomIndex]
}
